{
 "title": "Tor details",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Orport", "query": { "query": "label_values(orport)" } }
  ]
 },
 "panels": [
  {
   "title": "load onionskins / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(action, type) (rate(tor_relay_load_onionskins_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "{{action}} {{type}}"
    }
   ]
  },
  {
   "title": "circuits / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(state) (rate(tor_relay_circuits_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "intro1 / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(action) (rate(tor_relay_intro1_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "load socket / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(state) (rate(tor_relay_load_socket_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "rend1 / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(action) (rate(tor_relay_rend1_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections ipv4 / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(type, direction, state) (rate(tor_relay_connections{orport=\"$Orport\", family=\"ipv4\"}[$__rate_interval]))",
     "legendFormat": "{{type}} {{direction}} {{ſtate}}"
    }
   ]
  },
  {
   "title": "dos / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(type) (rate(tor_relay_dos_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections ipv6 / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(type, direction, state) (rate(tor_relay_connections{orport=\"$Orport\", family=\"ipv6\"}[$__rate_interval]))",
     "legendFormat": "{{type}} {{direction}} {{ſtate}}"
    }
   ]
  },
  {
   "title": "stream / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(type) (rate(tor_relay_streams_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "connections total ipv4 / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(type, state, direction) (rate(tor_relay_connections_total{orport=\"$Orport\", family=\"ipv4\"}[$__rate_interval]))",
     "legendFormat": "{{type}} {{state}} {{direction}}"
    }
   ]
  },
  {
   "title": "est intro / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(action) (rate(tor_relay_est_intro_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections total ipv6 / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(type, state, direction) (rate(tor_relay_connections_total{orport=\"$Orport\", family=\"ipv6\"}[$__rate_interval]))",
     "legendFormat": "{{type}} {{state}} {{direction}}"
    }
   ]
  },
  {
   "title": "est rend / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(action) (rate(tor_relay_est_rend_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "congestion control / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by(action, state) (rate(tor_relay_congestion_control{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "{{action}} {{state}}"
    }
   ]
  },
  {
   "title": "load global rate limit reached / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(side) (rate(tor_relay_load_global_rate_limit_reached_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "congestion control total / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by(action, state) (rate(tor_relay_congestion_control_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "{{action}} {{state}}"
    }
   ]
  },
  {
   "title": "exit dns query total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tor_relay_exit_dns_query_total{orport=\"$Orport\"}",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "load tcp exhaustion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "tor_relay_load_tcp_exhaustion_total{orport=\"$Orport\"}",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "exit dns error total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tor_relay_exit_dns_error_total{orport=\"$Orport\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "load oombytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(subsys, ) (rate(tor_relay_load_oom_bytes_total{orport=\"$Orport\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}