{
 "title": "Tor",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{device=\"enp8s0\"}[$__rate_interval])",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{device=\"enp8s0\"}[$__rate_interval])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) * 100) / on(label) sum(rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp8s0\"}[$__rate_interval])",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"enp8s0\"}[$__rate_interval])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "TCP sockets \"inuse\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "node_sockstat_TCP_inuse", "legendFormat": "IPv4" },
    { "expr": "node_sockstat_TCP6_inuse", "legendFormat": "IPv6" }
   ]
  },
  { "title": "Tor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(orport) (rate(tor_relay_traffic_bytes{direction=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Opened sockets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by(orport) (tor_relay_load_socket_total{state=\"opened\"})",
     "legendFormat": "{{label_name}}{{orport}}"
    }
   ]
  },
  {
   "title": "Connections init IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(orport) (tor_relay_connections{family=\"ipv4\", direction=\"initiated\"})",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "Connections init IPv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by(orport) (tor_relay_connections{family=\"ipv6\", direction=\"initiated\"})",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "Connections recv IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by(orport) (tor_relay_connections{family=\"ipv4\", direction=\"received\"})",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "Connections recv IPv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by(orport) (tor_relay_connections{family=\"ipv6\", direction=\"received\"})",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "ntor_v3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(orport) (rate(tor_relay_load_onionskins_total{action=\"processed\", type=\"ntor_v3\"}[$__rate_interval]))",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "Congestion (1 h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(orport) (rate(tor_relay_congestion_control[1h]))",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "Circuits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(orport) (rate(tor_relay_circuits_total[$__rate_interval]))",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "DoS circuits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(orport) (rate(tor_relay_dos_total{type=~\"circuit_killed_max_cell|circuit_rejected|circuit_killed_max_cell_outq\"}[$__rate_interval]))",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  { "title": "torutils iptables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "DROP syn IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(orport) (rate(torutils_syn_packets{ipver=\"4\"}[$__rate_interval]))",
     "legendFormat": "{{dpt}}"
    }
   ]
  },
  {
   "title": "DROP syn IPv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(orport) (rate(torutils_syn_packets{ipver=\"6\"}[$__rate_interval]))",
     "legendFormat": "{{dpt}}"
    }
   ]
  },
  {
   "title": "DROP state IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(state) (rate(torutils_state_packets{ipver=\"4\"}[$__rate_interval]))",
     "legendFormat": "{{dpt}}"
    }
   ]
  },
  {
   "title": "DROP state Pv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(state) (rate(torutils_state_packets{ipver=\"6\"}[$__rate_interval]))",
     "legendFormat": "{{dpt}}"
    }
   ]
  },
  {
   "title": "ipset ddos IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "torutils_ipset_total{ipver=\"4\", mode=\"ddos\"}",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "ipset ddos IPv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "torutils_ipset_total{ipver=\"6\", mode=\"ddos\"}",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "hashlimit ddos IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "torutils_hashlimit_total{ipver=\"4\", mode=\"ddos\"}",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "hashlimit ddos IPv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "torutils_hashlimit_total{ipver=\"6\", mode=\"ddos\"}",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "hashlimit rate IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "torutils_hashlimit_total{ipver=\"4\", mode=\"rate\"}",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "hashlimit rate IPv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "torutils_hashlimit_total{ipver=\"6\", mode=\"rate\"}",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  { "title": "torutils ipset timeout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "tor-ddos-443 IPv4",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "torutils_ipset_timeout_bucket{ipver=\"4\", orport=\"443\", mode=\"ddos\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tor-ddos-443 IPv6",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "torutils_ipset_timeout_bucket{ipver=\"6\", orport=\"443\", mode=\"ddos\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tor-ddos-8443 IPv4",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "torutils_ipset_timeout_bucket{ipver=\"4\", orport=\"8443\", mode=\"ddos\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tor-ddos-8443 IPv6",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "torutils_ipset_timeout_bucket{ipver=\"6\", orport=\"8443\", mode=\"ddos\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tor-ddos-9001 IPv4",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "torutils_ipset_timeout_bucket{ipver=\"4\", orport=\"9001\", mode=\"ddos\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tor-ddos-9001 IPv6",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "torutils_ipset_timeout_bucket{ipver=\"6\", orport=\"9001\", mode=\"ddos\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tor-ddos-9443 IPv4",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "torutils_ipset_timeout_bucket{ipver=\"4\", orport=\"9443\", mode=\"ddos\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tor-ddos-9443 IPv6",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "torutils_ipset_timeout_bucket{ipver=\"6\", orport=\"9443\", mode=\"ddos\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}