#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# set -x

# prints nftables counters and sets formatted for prometheus
# https://github.com/toralf/torutils

set -euf
export LANG=C.utf8
export PATH=/usr/sbin:/usr/bin:/sbin/:/bin

type jq nft >/dev/null

intervall=${1?INTERVALL NOT GIVEN}
if [[ ! $intervall =~ ^[0-9]+$ ]]; then
  echo "intervall is not an integer" >&2
  exit 1
fi

promfile=${2-}

lockfile="/tmp/$(basename $0).lock"
if [[ -s $lockfile ]]; then
  pid=$(<$lockfile)
  if kill -0 $pid &>/dev/null; then
    exit 0
  else
    echo "stale lock file, pid=$pid" >&2
  fi
fi
echo $$ >"$lockfile"

trap 'rm -f $lockfile ${promfile-}' INT QUIT TERM EXIT

i=0   # counter
nth=1 # scrape expensive data structures only every n-th time

while :; do
  start=$EPOCHSECONDS
  ((++i))

  tmpfile=$(mktemp /$(basename $0)_XXXXXX.tmp)
  {
    # -------- counters
    var="firewall_counter_packets"
    echo -e "# HELP $var All nftables named counter\n# TYPE $var gauge"

    nft -j list counters |
      jq -r ' (.nftables[] | select(has("counter")) | .counter | [.family, .table, .name, .packets]) | @tsv' |
      while read -r family table countername packets; do
        IFS='_' read -r resource ipver ext <<<$countername
        echo "$var{family=\"$family\",table=\"$table\",resource=\"$resource\",ipver=\"${ipver:-x}\",ext=\"${ext:-x}\"} $packets"
      done

    # -------- sets
    # query might become too expensive for short $intervall and big sets at tiny systems
    if ((nth == 1 || ++i % nth == 0)); then

      # sizes of all sets
      var="firewall_set_size"
      echo -e "# HELP $var All nftables set size\n# TYPE $var gauge"

      nft -j -nst list sets |
        jq -r '(.nftables[] | select(has("set")) | .set | [.family, .table, .name]) | @tsv' |
        while read -r family table setname; do
          IFS='_' read -r resource ipver ext <<<$setname
          n=$(
            nft -j -ns list set $family $table $setname |
              jq '.nftables[].set.elem // [] | length'
          )
          echo "$var{family=\"$family\",table=\"$table\",resource=\"$resource\",ipver=\"${ipver:-x}\",ext=\"${ext:-x}\"} $n"
        done

      # histogram , currently only the "ddos" set has a 24h timeout
      family="inet"
      table="ingress_filter"
      resource="ddos"
      ipver="v4"
      if nft -j -nst list set $family $table ${resource}_${ipver} &>/dev/null; then
        var="firewall_set_timeout"
        echo -e "# HELP $var A histogram of timeout values of a set\n# TYPE $var histogram"
        for ipver in v4 v6; do
          N=0
          while read -r hour count; do
            echo "${var}_bucket{family=\"$family\",table=\"$table\",resource=\"${resource}\",ipver=\"$ipver\",ext=\"x\",le=\"$hour\"} $((N += count))"
          done < <(
            # https://github.com/toralf/tor-relays/blob/main/playbooks/roles/info_common/tasks/firewall.yaml
            # A simple histogram can be generated by e.g.:
            nft -j -ns list set $family $table ddos_${ipver} |
              jq '.nftables[].set.elem[]? | .elem.expires / 3600 | floor' |
              jq -rs 'map(select(. >= 0 and . <= 23)) as $v | range(0; 24) as $h | "\($h) \([$v[] | select(. == $h)] | length)"'
          )

          echo "${var}_bucket{family=\"$family\",table=\"$table\",resource=\"${resource}\",ipver=\"${ipver}\",ext=\"x\",le=\"+Inf\"} $N"
          echo "${var}_count{family=\"$family\",table=\"$table\",resource=\"${resource}\",ipver=\"$ipver\",ext=\"x\"} $N"
        done
      fi
    fi
  } >$tmpfile

  if [[ -n $promfile ]]; then
    chmod a+r $tmpfile
    mv $tmpfile $promfile
  else
    cat $tmpfile
  fi

  if ((intervall == 0)); then
    break
  fi
  diff=$((EPOCHSECONDS - start))
  # adjust the scrape intervall if needed, sleep if possible
  if ((diff < intervall)); then
    if ((nth > 1)); then
      ((nth--))
    fi
    sleep $((intervall - diff))
  else
    if ((nth < 16)); then
      ((++nth))
    fi
  fi
done
