# https://github.com/toralf/torutils

# avoid (wrong) abuse complaints from hosters about egress "port scans"
# current *observed* threshold seems to be 150 connections within 4 min to a /22 network block
# set the limit/minute to 2/3 of it == 25

# become rude
# flush ruleset

# be nice
table ip egress_filter
flush table ip egress_filter

table ip egress_filter {

    set tor_nets_24 {
        type ipv4_addr;
        flags interval;
        elements = {
            45.84.107.0/24,
            96.9.98.0/24,
            109.70.100.0/24,
            171.25.193.0/24,
            185.220.101.0/24,
            192.42.116.0/24
        };
    }

    set tor_nets_22 {
        type ipv4_addr;
        flags interval;
        elements = {
            64.65.0.0/22,
            64.65.60.0/22
        };
    }

    # track network blocks
    counter egresslimit_v4   { packets 0 bytes 0 }
    set rate_limit_dst_net {
        type ipv4_addr;
        flags dynamic, timeout;
        timeout 4m;
    }

    chain output {
        type filter hook output priority filter; policy accept;

        oifname "lo" accept
        ct state established,related accept

        ip daddr @tor_nets_24 tcp flags syn ct state new \
        update @rate_limit_dst_net { ip daddr & 255.255.255.0 timeout 4m limit rate over 25/minute burst 25 packets } \
        counter name egresslimit_v4 \
        reject with icmp type port-unreachable

        ip daddr @tor_nets_22 tcp flags syn ct state new \
        update @rate_limit_dst_net { ip daddr & 255.255.252.0 timeout 4m limit rate over 25/minute burst 25 packets } \
        counter name egresslimit_v4 \
        reject with icmp type port-unreachable
    }
}
