{
 "title": "Tor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "node packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{device=\"enp8s0\"}[$__rate_interval])",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{device=\"enp8s0\"}[$__rate_interval])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "node traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp8s0\"}[$__rate_interval])",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"enp8s0\"}[$__rate_interval])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Tor load onion skins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(orport) (rate(tor_relay_load_onionskins_total{action=\"processed\", type=\"ntor_v3\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tor read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(orport) (rate(tor_relay_traffic_bytes{direction=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "node cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) * 100) / on(label) sum by(instance) (rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "node dropped SYN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(table) (rate(iptables_rule_packets_total{chain=\"INPUT\", table=\"filter\", rule=~\"-d 65.21.94.13/32 -p tcp -m tcp --dport 443 --tcp-flags FIN,SYN,RST,ACK SYN -m connlimit --connlimit-above 2 --connlimit-mask 32 --connlimit-saddr -j DROP|-d 65.21.94.13/32 -p tcp -m tcp --dport 443 --tcp-flags FIN,SYN,RST,ACK SYN -m hashlimit --hashlimit-above 1/hour --hashlimit-burst 1 --hashlimit-mode srcip,dstport --hashlimit-name tor-rate-443 --hashlimit-htable-expire 120000 -j DROP|-d 65.21.94.13/32 -p tcp -m tcp --dport 443 --tcp-flags FIN,SYN,RST,ACK SYN -m set --match-set tor-ddos-443 src -j DROP\"}[$__rate_interval]))",
     "legendFormat": "443"
    },
    {
     "expr": "sum by(table) (rate(iptables_rule_packets_total{chain=\"INPUT\", table=\"filter\", rule=~\"-d 65.21.94.13/32 -p tcp -m tcp --dport 8443 --tcp-flags FIN,SYN,RST,ACK SYN -m connlimit --connlimit-above 2 --connlimit-mask 32 --connlimit-saddr -j DROP|-d 65.21.94.13/32 -p tcp -m tcp --dport 8443 --tcp-flags FIN,SYN,RST,ACK SYN -m hashlimit --hashlimit-above 1/hour --hashlimit-burst 1 --hashlimit-mode srcip,dstport --hashlimit-name tor-rate-8443 --hashlimit-htable-expire 120000 -j DROP|-d 65.21.94.13/32 -p tcp -m tcp --dport 8443 --tcp-flags FIN,SYN,RST,ACK SYN -m set --match-set tor-ddos-8443 src -j DROP\"}[$__rate_interval]))",
     "legendFormat": "8443"
    },
    {
     "expr": "sum by(table) (rate(iptables_rule_packets_total{chain=\"INPUT\", table=\"filter\", rule=~\"-d 65.21.94.13/32 -p tcp -m tcp --dport 9001 --tcp-flags FIN,SYN,RST,ACK SYN -m connlimit --connlimit-above 2 --connlimit-mask 32 --connlimit-saddr -j DROP|-d 65.21.94.13/32 -p tcp -m tcp --dport 9001 --tcp-flags FIN,SYN,RST,ACK SYN -m hashlimit --hashlimit-above 1/hour --hashlimit-burst 1 --hashlimit-mode srcip,dstport --hashlimit-name tor-rate-9001 --hashlimit-htable-expire 120000 -j DROP|-d 65.21.94.13/32 -p tcp -m tcp --dport 9001 --tcp-flags FIN,SYN,RST,ACK SYN -m set --match-set tor-ddos-9001 src -j DROP\"}[$__rate_interval]))",
     "legendFormat": "9001"
    },
    {
     "expr": "sum by(table) (rate(iptables_rule_packets_total{chain=\"INPUT\", table=\"filter\", rule=~\"-m conntrack --ctstate INVALID -j DROP|-p tcp -m tcp ! --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j DROP\"}[$__rate_interval]))",
     "legendFormat": "state"
    },
    {
     "expr": "sum by(table) (rate(iptables_rule_packets_total{chain=\"INPUT\", table=\"filter\", rule=~\"-m conntrack --ctstate INVALID -j DROP\"}[$__rate_interval]))",
     "legendFormat": "ctstate"
    },
    {
     "expr": "rate(node_netstat_TcpExt_ListenDrops[$__rate_interval])",
     "legendFormat": "Drops"
    }
   ]
  },
  {
   "title": "Tor DDoS circuits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(orport) (rate(tor_relay_dos_total[$__rate_interval]))",
     "legendFormat": "{{orport}}"
    }
   ]
  },
  {
   "title": "Tor opened sockets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max by(orport) (tor_relay_load_socket_total{state=\"opened\"})",
     "legendFormat": "{{label_name}}{{orport}}"
    }
   ]
  }
 ]
}