{
 "title": "Tor Snowflake",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "label": "Job",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total,job)"
    }
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tor_snowflake_proxy_connections_total{job=~\"$Job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proxy Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tor_snowflake_proxy_connections_total{instance=~\"$Instance\"}[1h]) * 3600",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic Inbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(tor_snowflake_proxy_traffic_inbound_bytes_total{instance=~\"$Instance\"}[1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic Outbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(tor_snowflake_proxy_traffic_outbound_bytes_total{instance=~\"$Instance\"}[1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open Fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(process_open_fds{instance=~\"$Instance\"}[1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(process_cpu_seconds_total{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}